### ISSUE TITLE
Repair kits do not work

### ISSUE THREAD

**Issue by BennUzi** [qbcore-framework/qb-vehiclefailure#23]
Normal repair kit and advanced repair kit do not work. 
Isbackengine on Github throws an error, needs to be updated.

**Comment by janee431** [comment]
They only work when your engine is broken enough to be repaired.

**Comment by ShaAlexander** [comment]
Sorry not to be ignorant but i also have this issue, even when the engine is at 50%, 80% and 100% death. The used notification pops up but then nothing, not even an error. :(

**Comment by ShaAlexander** [comment]
> Sorry not to be ignorant but i also have this issue, even when the engine is at 50%, 80% and 100% death. The used notification pops up but then nothing, not even an error. :(

I was ignorant, had to update the script sawry!
