### ISSUE TITLE
Advanced Repair Kits

### ISSUE THREAD

**Issue by RagedxMike** [qbcore-framework/qb-vehiclefailure#52]
So, I play in a server where advanced repair kits can repair cars fully, like body and engine. When I use the script on my server, it only repairs the engine. Is there any guide that can help me change it to repair the whole car?

**Comment by GitMocha** [comment]
Are you using "Advanced Repair Kit" or just "Repair Kit"? There's 2 kits.

**Comment by RagedxMike** [comment]
Im using the advanced repair kit. it will repair the engine, but I would like to make it repair the body too.
