### ISSUE TITLE
[BUG] Can't drive nor exit a vehicle

### ISSUE THREAD

**Issue by RKDimitrov** [qbcore-framework/qb-vehiclefailure#53]
**Describe the bug**
When getting in a vehicle I can't drive nor exit it. Deleting it (/dv) lets me exit the vehicle, however the player model then cant fight and do almost nothing. I found that when you emote with "/e cigar" it solves that problem. Fortunately enough I want it all gone. In old Fivem documents I found that it may have to do something with Realistic Car Failure so that's why I am reaching out here.

**To Reproduce**
1. Go into a vehicle
2. Can't drive it nor exit it
3. See the errors in console
4. Delete it, so you can be free
5. Emote with "/e cigar"
6. Fixed it for yourself

**Screenshots**
![image](https://github.com/qbcore-framework/qb-vehiclefailure/assets/99919461/e13637cc-776c-4da1-9e00-42f49f8615fa)

**Questions (please complete the following information):**
 - When you last updated: 5 days ago
 - Are you using custom resource? which ones? Yes, I am using a lot.
 - Have you renamed `qb-` to something custom? No

**Additional context**
I have zero idea where is it coming from so if the problem is not from qb-vehiclefailure, please tell me where to go.

**Comment by Spenjunior** [comment]
I’m also having the same problem 
-when a player is in a vehicle sometimes you can’t drive can’t exit the vehicle
-when a player is on foot sometimes you can’t punch or do anything only walk 
To fix all of that above is to put hand up and hand down using X the default hands up or cancel animation qbcore framework
I need help to fix that problem so player don’t have to do that all the time. Thanks

**Comment by MafewTM** [comment]
And everyone here is using a fresh, unedited version of the resource?

**Comment by Bellck** [comment]
Same issues here, especially with one of one cars, pull them out of JG-Advancedgarages and crash.
